import type { SourceConfig } from '../sources/types.js';

/** Canonical registry entries — mirrored in docs/DATA_SOURCES.md. */
export const SOURCE_CONFIGS: readonly SourceConfig[] = [
  {
    id: 'tt11-blades-penholder',
    name: 'TableTennis11 — penholder blades',
    listingUrl: 'https://tabletennis11.com/en/blades-penholder',
    categories: ['blade'],
    role: 'catalog-photos-secondary',
    selectorNotes: [
      'Cloudflare challenge blocks automated GET (2026-07).',
      'Prefer dandoy-blades / prott for live ingestion until browser export exists.',
    ],
    rateLimitMs: 1500,
    cloudflareBlocked: true,
  },
  {
    id: 'tt11-blades',
    name: 'TableTennis11 — blades',
    listingUrl: 'https://tabletennis11.com/en/blades',
    categories: ['blade'],
    role: 'catalog-photos-primary',
    selectorNotes: [
      'Cloudflare challenge blocks automated GET (2026-07).',
      'Manual HTML export or alternate source required for live scrape.',
    ],
    rateLimitMs: 1500,
    cloudflareBlocked: true,
  },
  {
    id: 'tt11-rubbers',
    name: 'TableTennis11 — rubbers',
    listingUrl: 'https://tabletennis11.com/en/rubbers',
    categories: ['rubber'],
    role: 'catalog-photos-primary',
    selectorNotes: [
      'Cloudflare challenge blocks automated GET (2026-07).',
    ],
    rateLimitMs: 1500,
    cloudflareBlocked: true,
  },
  {
    id: 'tabletennis-reviews',
    name: 'Table Tennis Reviews',
    listingUrl: 'https://tabletennis-reviews.com/',
    categories: ['blade', 'rubber', 'other'],
    role: 'reviews',
    selectorNotes: [
      'TODO: review index / post links',
      'TODO: extract product mentions; media only if rights allow download',
    ],
    rateLimitMs: 2000,
  },
  {
    id: 'ttgearlab-database',
    name: 'TTGearLab — database category',
    listingUrl: 'https://ttgearlab.com/category/database/',
    categories: ['blade', 'rubber', 'other'],
    role: 'specs-lab',
    selectorNotes: [
      'TODO: category pagination',
      'TODO: measured attributes → provenance bags',
    ],
    rateLimitMs: 2000,
  },
  {
    id: 'ittf-equipment-approval',
    name: 'ITTF — equipment approval',
    listingUrl: 'https://equipment.ittf.com/#/equipment/approval',
    categories: ['blade', 'rubber', 'ball', 'other'],
    role: 'official-approval',
    selectorNotes: [
      'Public API: https://ittf-admin-api.azurewebsites.net (swagger /swagger/docs/v1)',
      'Racket coverings: GET /api/Equipment_RacketCoverings/all_list (custom_filter=[] + sortby=BrandName)',
      'Siblings: Equipment_Balls / Tables / Nets / Floors all_list with type-specific sortby',
      'No dedicated Blades/Adhesives controllers in swagger (EquipmentTypes includes Rackets)',
      'Batch monitor: pnpm ittf -- snapshot|annotate (see scrapers README)',
    ],
    rateLimitMs: 2500,
  },
  {
    id: 'ittf-racket-coverings',
    name: 'ITTF — racket coverings',
    listingUrl: 'https://equipment.ittf.com/#/equipment/racket_coverings',
    categories: ['rubber'],
    role: 'official-approval',
    selectorNotes: [
      'LIVE API: /api/Equipment_RacketCoverings/all_list → rows + Count',
      'Fields: EquipmentCode, ApprovalStatus, IsActive, ExpiresOn, BrandName, EquipmentName, ImageList, PimpleType',
      'Stable key: EquipmentCode when present; else EquipmentRacketCoveringId',
      'CLI: pnpm ittf -- snapshot && pnpm ittf -- annotate --seed-fixtures',
    ],
    rateLimitMs: 2500,
  },
  {
    id: 'tt-spin-rubbers',
    name: 'TT-Spin — rubbers',
    listingUrl: 'https://www.tt-spin.com/table-tennis-rubbers/',
    categories: ['rubber'],
    role: 'catalog-photos-secondary',
    selectorNotes: ['TODO: rubber grid / pagination', 'TODO: product image URLs for download'],
    rateLimitMs: 2000,
  },
  {
    id: 'prott-rubbers',
    name: 'ProTT — rubbers',
    listingUrl: 'https://www.prott.vip/Product-List.aspx?producttype=2',
    categories: ['rubber'],
    role: 'catalog-photos-secondary',
    selectorNotes: [
      'ASP.NET Product-List.aspx — watch ViewState / page index query params',
      'TODO: product detail links + images',
    ],
    rateLimitMs: 2000,
  },
  {
    id: 'prott-blades',
    name: 'ProTT — blades',
    listingUrl: 'https://www.prott.vip/Product-List.aspx?producttype=12',
    categories: ['blade'],
    role: 'catalog-photos-secondary',
    selectorNotes: [
      'Same list pattern as prott-rubbers with producttype=12',
      'TODO: product detail links + images',
    ],
    rateLimitMs: 2000,
  },
  {
    id: 'dandoy-blades',
    name: 'Dandoy Sports — blades',
    listingUrl: 'https://www.dandoy-sports.com/blades.html',
    categories: ['blade'],
    role: 'catalog-photos-primary',
    selectorNotes: [
      'LIVE: Magento li.product-item + PDP gallery "full" URLs',
      'Pagination: blades.html?p=N (≈5 pages)',
    ],
    rateLimitMs: 1000,
  },
  {
    id: 'dandoy-rubbers',
    name: 'Dandoy Sports — rubbers',
    listingUrl: 'https://www.dandoy-sports.com/rubbers.html',
    categories: ['rubber'],
    role: 'catalog-photos-primary',
    selectorNotes: [
      'LIVE: same Magento pattern as dandoy-blades',
      'Pagination: rubbers.html?p=N (≈5 pages)',
    ],
    rateLimitMs: 1000,
  },
  {
    id: 'vpsport-gomas-lisas',
    name: 'VP Sport — gomas lisas',
    listingUrl: 'https://www.vpsport.cl/gomas-lisas',
    categories: ['rubber'],
    role: 'catalog-photos-primary',
    selectorNotes: [
      'LIVE: Jumpseller article/product-block + cdnx.jumpseller.com thumbs',
      'Pagination: ?page=N',
    ],
    rateLimitMs: 1000,
  },
  {
    id: 'vpsport-maderos-clasicos',
    name: 'VP Sport — maderos clásicos',
    listingUrl: 'https://www.vpsport.cl/maderos-clasicos',
    categories: ['blade'],
    role: 'catalog-photos-primary',
    selectorNotes: ['LIVE: same Jumpseller pattern as vpsport-gomas-lisas'],
    rateLimitMs: 1000,
  },
  {
    id: 'vpsport-maderos-japones',
    name: 'VP Sport — maderos japoneses',
    listingUrl: 'https://www.vpsport.cl/maderos-japones',
    categories: ['blade'],
    role: 'catalog-photos-secondary',
    selectorNotes: ['LIVE: Jumpseller category'],
    rateLimitMs: 1000,
  },
  {
    id: 'vpsport-maderos-lapiceros',
    name: 'VP Sport — maderos lapiceros',
    listingUrl: 'https://www.vpsport.cl/maderos-lapiceros',
    categories: ['blade'],
    role: 'catalog-photos-secondary',
    selectorNotes: ['LIVE: Jumpseller penhold blades'],
    rateLimitMs: 1000,
  },
  {
    id: 'vpsport-poros-cortos',
    name: 'VP Sport — poros cortos',
    listingUrl: 'https://www.vpsport.cl/poros-cortos',
    categories: ['rubber'],
    role: 'catalog-photos-secondary',
    selectorNotes: ['LIVE: short pips category'],
    rateLimitMs: 1000,
  },
  {
    id: 'vpsport-poros-largos',
    name: 'VP Sport — poros largos',
    listingUrl: 'https://www.vpsport.cl/poros-largos',
    categories: ['rubber'],
    role: 'catalog-photos-secondary',
    selectorNotes: ['LIVE: long pips category'],
    rateLimitMs: 1000,
  },
  {
    id: 'vpsport-gomas-anti-topspin',
    name: 'VP Sport — gomas anti-topspin',
    listingUrl: 'https://www.vpsport.cl/gomas/anti-topspin',
    categories: ['rubber'],
    role: 'catalog-photos-secondary',
    selectorNotes: ['LIVE: anti-topspin category'],
    rateLimitMs: 1000,
  },
  {
    id: 'zonatt-maderas',
    name: 'ZonaTT — maderas',
    listingUrl: 'https://www.zonatt.com/es/maderas-de-tenis-de-mesa',
    categories: ['blade'],
    role: 'catalog-photos-primary',
    selectorNotes: [
      'LIVE: inventory from sitemap.php (all maderas PDPs, incl. OOS/discontinued)',
      'Listing HTML + ajax show-list only for mango/thumb hints (not stock filter)',
      'PDP og:image (/img/zonatt/…); mango AN/FL/ST/PH',
      'EXTRA_PRODUCT_URLS for PDPs missing from sitemap (e.g. Ai Fukuhara Pro ZLF)',
    ],
    rateLimitMs: 1200,
  },
  {
    id: 'zonatt-gomas',
    name: 'ZonaTT — gomas',
    listingUrl: 'https://www.zonatt.com/es/gomas-de-tenis-de-mesa',
    categories: ['rubber'],
    role: 'catalog-photos-primary',
    selectorNotes: [
      'LIVE: inventory from sitemap.php (all gomas PDPs, incl. OOS/discontinued)',
      'Ajax category Id=1 for listing hints; PDP og:image',
      'Priority EXTRA: Hurricane 3 Neo Provincial Blue Sponge 39, Dr.Neubauer Killer Pro',
    ],
    rateLimitMs: 1200,
  },
  {
    id: 'cl-rubber-seeds',
    name: 'CL shop rubber seeds (Bushido / Foxhara)',
    listingUrl: 'https://www.bushido.cl/producto/dhs-hurricane-3-neo/',
    categories: ['rubber'],
    role: 'catalog-photos-secondary',
    selectorNotes: [
      'LIVE: explicit WooCommerce PDP URLs only (no category crawl yet)',
      'Seeds: Bushido H3 Neo; Foxhara H3 Neo Soft blue Provincial Team',
      'tabletennis11.com PDPs remain Cloudflare-blocked — do not rely on automated GET',
    ],
    rateLimitMs: 1000,
  },
] as const;

export function getSourceConfig(id: string): SourceConfig | undefined {
  return SOURCE_CONFIGS.find((source) => source.id === id);
}
